"""Curated dictionary of public companies and how the show refers to them.

Each entry: (ticker, display name, aliases, options)
  aliases  – "|"-separated. Prefix an alias with "?" when the word is also an
             ordinary English word or a common non-company usage (Target, Gap,
             Block…); such aliases only count when a stock-market cue word
             appears nearby. Suffix "@YYYY-MM-DD" limits an alias to mentions on
             or after that date (e.g. Reddit only became a public company in
             March 2024). Suffix "<YYYY-MM-DD" limits an alias to mentions
             before that date (a brand that changed owners).
  options  – domain (for logos), sector, yf (Yahoo Finance symbol when it
             differs from the ticker), delisted (ISO date), etf (True for
             funds), country.
"""
from __future__ import annotations

ENTRIES: list[tuple] = []


def E(ticker: str, name: str, aliases: str, **opt):
    ENTRIES.append((ticker, name, aliases, opt))


# --- Mega-cap tech -----------------------------------------------------------
E("AAPL", "Apple", "Apple|Apple Inc|Apple's|iPhone maker|iPhone|iPhones", domain="apple.com", sector="Technology")
E("MSFT", "Microsoft", "Microsoft|Microsoft's|Xbox|LinkedIn|Copilot", domain="microsoft.com", sector="Technology")
E("GOOGL", "Alphabet (Google)", "Alphabet|Google|Google's|Alphabet's|YouTube|Waymo|Gemini AI|Google Gemini", domain="abc.xyz", sector="Communication Services")
E("AMZN", "Amazon", "Amazon|Amazon's|AWS|Amazon Web Services|Whole Foods|Prime Day", domain="amazon.com", sector="Consumer Discretionary")
E("META", "Meta Platforms", "Meta|Facebook|Meta Platforms|Instagram|WhatsApp|Facebook's|Meta's|Threads app", domain="meta.com", sector="Communication Services")
E("NVDA", "Nvidia", "Nvidia|NVIDIA|Nvidia's|NVIDIA's|Invidia|In Vidia", domain="nvidia.com", sector="Technology")
E("TSLA", "Tesla", "Tesla|Tesla's|Cybertruck", domain="tesla.com", sector="Consumer Discretionary")
E("NFLX", "Netflix", "Netflix|Netflix's", domain="netflix.com", sector="Communication Services")
E("AVGO", "Broadcom", "Broadcom", domain="broadcom.com", sector="Technology")
E("ORCL", "Oracle", "Oracle|Oracle's", domain="oracle.com", sector="Technology")
E("CRM", "Salesforce", "Salesforce|Sales Force|Slack", domain="salesforce.com", sector="Technology")
E("ADBE", "Adobe", "Adobe", domain="adobe.com", sector="Technology")
E("INTC", "Intel", "Intel|Intel's", domain="intel.com", sector="Technology")
E("AMD", "AMD", "AMD|Advanced Micro Devices", domain="amd.com", sector="Technology")
E("MU", "Micron", "Micron|Micron Technology", domain="micron.com", sector="Technology")
E("QCOM", "Qualcomm", "Qualcomm", domain="qualcomm.com", sector="Technology")
E("TSM", "TSMC", "TSMC|Taiwan Semiconductor|Taiwan Semi", domain="tsmc.com", sector="Technology", country="TW")
E("ASML", "ASML", "ASML", domain="asml.com", sector="Technology", country="NL")
E("ARM", "Arm Holdings", "Arm Holdings|?Arm@2023-09-14", domain="arm.com", sector="Technology", country="UK")
E("SMCI", "Super Micro Computer", "Super Micro|Supermicro|Super Micro Computer|SMCI", domain="supermicro.com", sector="Technology")
E("DELL", "Dell", "Dell|Dell Technologies", domain="dell.com", sector="Technology")
E("HPQ", "HP Inc.", "HP Inc|Hewlett-Packard|?HP", domain="hp.com", sector="Technology")
E("HPE", "Hewlett Packard Enterprise", "Hewlett Packard Enterprise", domain="hpe.com", sector="Technology")
E("IBM", "IBM", "IBM", domain="ibm.com", sector="Technology")
E("CSCO", "Cisco", "Cisco", domain="cisco.com", sector="Technology")
E("TXN", "Texas Instruments", "Texas Instruments", domain="ti.com", sector="Technology")
E("MRVL", "Marvell", "Marvell", domain="marvell.com", sector="Technology")
E("LRCX", "Lam Research", "Lam Research", domain="lamresearch.com", sector="Technology")
E("AMAT", "Applied Materials", "Applied Materials", domain="appliedmaterials.com", sector="Technology")
E("KLAC", "KLA", "KLA Corp|KLA Corporation|KLA-Tencor", domain="kla.com", sector="Technology")
E("ANET", "Arista Networks", "Arista", domain="arista.com", sector="Technology")
E("NOW", "ServiceNow|Service Now", "ServiceNow|Service Now", domain="servicenow.com", sector="Technology")
E("WDAY", "Workday", "Workday", domain="workday.com", sector="Technology")
E("INTU", "Intuit", "Intuit|TurboTax", domain="intuit.com", sector="Technology")
E("ADSK", "Autodesk", "Autodesk", domain="autodesk.com", sector="Technology")
E("TEAM", "Atlassian", "Atlassian", domain="atlassian.com", sector="Technology")
E("TWLO", "Twilio", "Twilio", domain="twilio.com", sector="Technology")
E("OKTA", "Okta", "Okta", domain="okta.com", sector="Technology")
E("CRWD", "CrowdStrike", "CrowdStrike|Crowdstrike|Crowd Strike", domain="crowdstrike.com", sector="Technology")
E("PANW", "Palo Alto Networks", "Palo Alto Networks", domain="paloaltonetworks.com", sector="Technology")
E("FTNT", "Fortinet", "Fortinet", domain="fortinet.com", sector="Technology")
E("ZS", "Zscaler", "Zscaler", domain="zscaler.com", sector="Technology")
E("NET", "Cloudflare", "Cloudflare", domain="cloudflare.com", sector="Technology")
E("DDOG", "Datadog", "Datadog", domain="datadoghq.com", sector="Technology")
E("MDB", "MongoDB", "MongoDB", domain="mongodb.com", sector="Technology")
E("SNOW", "Snowflake", "?Snowflake", domain="snowflake.com", sector="Technology")
E("PLTR", "Palantir", "Palantir|Palantir Technologies|Palantier|Palanteer", domain="palantir.com", sector="Technology")
E("AI", "C3.ai", "C3.ai|C3 AI", domain="c3.ai", sector="Technology")
E("SOUN", "SoundHound AI", "SoundHound", domain="soundhound.com", sector="Technology")
E("APP", "AppLovin", "AppLovin", domain="applovin.com", sector="Technology")
E("TTD", "The Trade Desk", "Trade Desk", domain="thetradedesk.com", sector="Technology")
E("U", "Unity Software", "Unity Software|Unity Technologies", domain="unity.com", sector="Technology")
E("ZM", "Zoom", "Zoom Video|?Zoom", domain="zoom.us", sector="Technology")
E("DOCU", "DocuSign", "DocuSign|Docusign", domain="docusign.com", sector="Technology")
E("DBX", "Dropbox", "Dropbox", domain="dropbox.com", sector="Technology")
E("BOX", "Box", "?Box Inc", domain="box.com", sector="Technology")
E("ASAN", "Asana", "Asana", domain="asana.com", sector="Technology")
E("GTLB", "GitLab", "GitLab", domain="gitlab.com", sector="Technology")
E("PATH", "UiPath", "UiPath", domain="uipath.com", sector="Technology")
E("BBAI", "BigBear.ai", "BigBear", domain="bigbear.ai", sector="Technology")
E("SHOP", "Shopify", "Shopify", domain="shopify.com", sector="Technology", country="CA")
E("SQ", "Block (Square)", "Block Inc|Square Inc|?Block|?Square|Cash App|Afterpay", domain="block.xyz", sector="Financials", yf="XYZ")
E("PYPL", "PayPal", "PayPal|Paypal|Pay Pal|Venmo", domain="paypal.com", sector="Financials")
E("AFRM", "Affirm", "?Affirm", domain="affirm.com", sector="Financials")
E("UPST", "Upstart", "?Upstart", domain="upstart.com", sector="Financials")
E("SOFI", "SoFi", "SoFi|Sofi|So-Fi|So Fi", domain="sofi.com", sector="Financials")
E("HOOD", "Robinhood", "Robinhood|Robinhood's|?Robin Hood", domain="robinhood.com", sector="Financials")
E("COIN", "Coinbase|Coin Base", "Coinbase|Coin Base", domain="coinbase.com", sector="Financials")
E("MSTR", "Strategy (MicroStrategy)", "MicroStrategy|Microstrategy|Micro Strategy|MicroStrategy's", domain="strategy.com", sector="Technology")
E("MARA", "MARA Holdings", "Marathon Digital|MARA Holdings", domain="mara.com", sector="Financials")
E("RIOT", "Riot Platforms", "Riot Platforms|Riot Blockchain", domain="riotplatforms.com", sector="Financials")
E("CLSK", "CleanSpark", "CleanSpark", domain="cleanspark.com", sector="Financials")
E("GLXY", "Galaxy Digital", "Galaxy Digital", domain="galaxy.com", sector="Financials")
E("CRCL", "Circle Internet", "Circle Internet|?Circle@2025-06-05", domain="circle.com", sector="Financials")
E("BLSH", "Bullish", "?Bullish@2025-08-13", domain="bullish.com", sector="Financials")

# --- Internet / consumer platforms -----------------------------------------
E("UBER", "Uber", "Uber|Uber's|Uber Eats", domain="uber.com", sector="Industrials")
E("LYFT", "Lyft", "Lyft", domain="lyft.com", sector="Industrials")
E("ABNB", "Airbnb|AirBnB|Air BnB|Air B&B|Air B and B", "Airbnb|AirBnB|Air BnB|Air B&B|Air B and B", domain="airbnb.com", sector="Consumer Discretionary")
E("DASH", "DoorDash", "DoorDash|Doordash|Door Dash", domain="doordash.com", sector="Consumer Discretionary")
E("SPOT", "Spotify", "Spotify", domain="spotify.com", sector="Communication Services", country="SE")
E("ROKU", "Roku", "Roku", domain="roku.com", sector="Communication Services")
E("SNAP", "Snap", "Snapchat|Snap Inc|?Snap", domain="snap.com", sector="Communication Services")
E("PINS", "Pinterest", "Pinterest", domain="pinterest.com", sector="Communication Services")
E("RDDT", "Reddit", "Reddit@2024-03-21", domain="reddit.com", sector="Communication Services")
E("TWTR", "Twitter", "?Twitter|Twitter Inc", domain="x.com", sector="Communication Services", delisted="2022-10-27")
E("RBLX", "Roblox", "Roblox", domain="roblox.com", sector="Communication Services")
E("EA", "Electronic Arts", "Electronic Arts", domain="ea.com", sector="Communication Services")
E("TTWO", "Take-Two Interactive", "Take-Two|Take Two Interactive", domain="take2games.com", sector="Communication Services")
E("ATVI", "Activision Blizzard", "Activision", domain="activisionblizzard.com", sector="Communication Services", delisted="2023-10-13")
E("MTCH", "Match Group", "Match Group|Tinder", domain="mtch.com", sector="Communication Services")
E("BMBL", "Bumble", "Bumble", domain="bumble.com", sector="Communication Services")
E("DUOL", "Duolingo", "Duolingo", domain="duolingo.com", sector="Technology")
E("COUR", "Coursera", "Coursera", domain="coursera.org", sector="Consumer Discretionary")
E("CHGG", "Chegg", "Chegg", domain="chegg.com", sector="Consumer Discretionary")
E("PTON", "Peloton", "Peloton", domain="onepeloton.com", sector="Consumer Discretionary")
E("ETSY", "Etsy", "Etsy", domain="etsy.com", sector="Consumer Discretionary")
E("EBAY", "eBay", "eBay|Ebay|E-Bay|E Bay", domain="ebay.com", sector="Consumer Discretionary")
E("W", "Wayfair", "Wayfair", domain="wayfair.com", sector="Consumer Discretionary")
E("CHWY", "Chewy", "Chewy", domain="chewy.com", sector="Consumer Discretionary")
E("CVNA", "Carvana", "Carvana", domain="carvana.com", sector="Consumer Discretionary")
E("OPEN", "Opendoor", "Opendoor", domain="opendoor.com", sector="Real Estate")
E("Z", "Zillow", "Zillow", domain="zillow.com", sector="Real Estate")
E("RDFN", "Redfin", "Redfin", domain="redfin.com", sector="Real Estate", delisted="2025-07-01")
E("COMP", "Compass", "?Compass Inc", domain="compass.com", sector="Real Estate")
E("CART", "Instacart", "Instacart|Maplebear", domain="instacart.com", sector="Consumer Staples")
E("TOST", "Toast", "?Toast Inc", domain="toasttab.com", sector="Technology")
E("BABA", "Alibaba", "Alibaba", domain="alibaba.com", sector="Consumer Discretionary", country="CN")
E("JD", "JD.com", "JD.com", domain="jd.com", sector="Consumer Discretionary", country="CN")
E("PDD", "PDD Holdings (Temu)", "PDD Holdings|Pinduoduo|Temu", domain="pddholdings.com", sector="Consumer Discretionary", country="CN")
E("BIDU", "Baidu", "Baidu", domain="baidu.com", sector="Communication Services", country="CN")
E("TCEHY", "Tencent", "Tencent", domain="tencent.com", sector="Communication Services", country="CN")
E("NTES", "NetEase", "NetEase", domain="netease.com", sector="Communication Services", country="CN")
E("SE", "Sea Limited", "Sea Limited|Sea Ltd|Shopee", domain="sea.com", sector="Consumer Discretionary", country="SG")
E("GRAB", "Grab", "Grab Holdings", domain="grab.com", sector="Industrials", country="SG")
E("CPNG", "Coupang", "Coupang", domain="coupang.com", sector="Consumer Discretionary", country="KR")
E("MELI", "MercadoLibre", "MercadoLibre|Mercado Libre", domain="mercadolibre.com", sector="Consumer Discretionary", country="AR")
E("NU", "Nu Holdings", "Nubank|Nu Holdings", domain="nu.com.br", sector="Financials", country="BR")
E("DIDI", "DiDi", "DiDi|Didi Chuxing|Didi", domain="didiglobal.com", sector="Industrials", country="CN", delisted="2022-06-10")

# --- Autos / EV --------------------------------------------------------------
E("F", "Ford", "Ford Motor|?Ford", domain="ford.com", sector="Consumer Discretionary")
E("GM", "General Motors", "General Motors|?GM", domain="gm.com", sector="Consumer Discretionary")
E("STLA", "Stellantis", "Stellantis|Chrysler|Jeep", domain="stellantis.com", sector="Consumer Discretionary", country="NL")
E("TM", "Toyota", "Toyota", domain="toyota.com", sector="Consumer Discretionary", country="JP")
E("HMC", "Honda", "Honda", domain="honda.com", sector="Consumer Discretionary", country="JP")
E("RACE", "Ferrari", "Ferrari", domain="ferrari.com", sector="Consumer Discretionary", country="IT")
E("RIVN", "Rivian", "Rivian", domain="rivian.com", sector="Consumer Discretionary")
E("LCID", "Lucid", "Lucid Motors|Lucid Group|?Lucid", domain="lucidmotors.com", sector="Consumer Discretionary")
E("NIO", "NIO", "NIO|Nio", domain="nio.com", sector="Consumer Discretionary", country="CN")
E("XPEV", "XPeng", "XPeng|Xpeng", domain="xiaopeng.com", sector="Consumer Discretionary", country="CN")
E("LI", "Li Auto", "Li Auto", domain="lixiang.com", sector="Consumer Discretionary", country="CN")
E("BYDDY", "BYD", "BYD", domain="byd.com", sector="Consumer Discretionary", country="CN")
E("NKLA", "Nikola", "Nikola", domain="nikolamotor.com", sector="Industrials", delisted="2025-02-19")
E("FSR", "Fisker", "Fisker", domain="fiskerinc.com", sector="Consumer Discretionary", delisted="2024-03-25")
E("HTZ", "Hertz", "Hertz", domain="hertz.com", sector="Industrials")
E("CAR", "Avis Budget", "Avis Budget|Avis", domain="avisbudgetgroup.com", sector="Industrials")
E("KMX", "CarMax", "CarMax", domain="carmax.com", sector="Consumer Discretionary")
E("AZO", "AutoZone", "AutoZone", domain="autozone.com", sector="Consumer Discretionary")
E("ORLY", "O'Reilly Automotive", "O'Reilly", domain="oreillyauto.com", sector="Consumer Discretionary")
E("HOG", "Harley-Davidson", "Harley-Davidson|Harley Davidson", domain="harley-davidson.com", sector="Consumer Discretionary")
E("PLUG", "Plug Power", "Plug Power", domain="plugpower.com", sector="Industrials")
E("CHPT", "ChargePoint", "ChargePoint", domain="chargepoint.com", sector="Industrials")
E("QS", "QuantumScape", "QuantumScape", domain="quantumscape.com", sector="Consumer Discretionary")

# --- Retail / consumer -------------------------------------------------------
E("WMT", "Walmart", "Walmart|Walmart's|Wal-Mart", domain="walmart.com", sector="Consumer Staples")
E("TGT", "Target", "?Target", domain="target.com", sector="Consumer Staples")
E("COST", "Costco", "Costco", domain="costco.com", sector="Consumer Staples")
E("HD", "Home Depot", "Home Depot", domain="homedepot.com", sector="Consumer Discretionary")
E("LOW", "Lowe's", "Lowe's|Lowes", domain="lowes.com", sector="Consumer Discretionary")
E("KR", "Kroger", "Kroger", domain="kroger.com", sector="Consumer Staples")
E("ACI", "Albertsons", "Albertsons", domain="albertsonscompanies.com", sector="Consumer Staples")
E("DG", "Dollar General", "Dollar General", domain="dollargeneral.com", sector="Consumer Staples")
E("DLTR", "Dollar Tree", "Dollar Tree|Family Dollar", domain="dollartree.com", sector="Consumer Staples")
E("FIVE", "Five Below", "Five Below", domain="fivebelow.com", sector="Consumer Discretionary")
E("BBY", "Best Buy", "Best Buy", domain="bestbuy.com", sector="Consumer Discretionary")
E("M", "Macy's", "Macy's|Macys", domain="macys.com", sector="Consumer Discretionary")
E("JWN", "Nordstrom", "Nordstrom", domain="nordstrom.com", sector="Consumer Discretionary", delisted="2025-05-20")
E("KSS", "Kohl's", "Kohl's|Kohls", domain="kohls.com", sector="Consumer Discretionary")
E("BBBY", "Bed Bath & Beyond", "Bed Bath & Beyond|Bed Bath and Beyond|Bed Bath", domain="bedbathandbeyond.com", sector="Consumer Discretionary", delisted="2023-05-03")
E("GME", "GameStop", "GameStop|Gamestop|Game Stop|GME", domain="gamestop.com", sector="Consumer Discretionary")
E("AMC", "AMC Entertainment", "AMC Entertainment|AMC Theatres|AMC", domain="amctheatres.com", sector="Communication Services")
E("TJX", "TJX Companies", "TJX|T.J. Maxx|TJ Maxx|Marshalls", domain="tjx.com", sector="Consumer Discretionary")
E("ROST", "Ross Stores", "Ross Stores", domain="rossstores.com", sector="Consumer Discretionary")
E("BURL", "Burlington Stores", "Burlington Stores|Burlington", domain="burlington.com", sector="Consumer Discretionary")
E("BJ", "BJ's Wholesale", "BJ's", domain="bjs.com", sector="Consumer Staples")
E("OLLI", "Ollie's", "Ollie's", domain="ollies.us", sector="Consumer Discretionary")
E("ULTA", "Ulta Beauty", "Ulta", domain="ulta.com", sector="Consumer Discretionary")
E("EL", "Estée Lauder", "Estee Lauder|Estée Lauder", domain="elcompanies.com", sector="Consumer Staples")
E("NKE", "Nike", "Nike|Nike's", domain="nike.com", sector="Consumer Discretionary")
E("LULU", "Lululemon", "Lululemon|lululemon|Lulu Lemon", domain="lululemon.com", sector="Consumer Discretionary")
E("UAA", "Under Armour", "Under Armour", domain="underarmour.com", sector="Consumer Discretionary")
E("CROX", "Crocs", "Crocs", domain="crocs.com", sector="Consumer Discretionary")
E("DECK", "Deckers", "Deckers|Hoka", domain="deckers.com", sector="Consumer Discretionary")
E("ONON", "On Holding", "On Holding|On Running", domain="on.com", sector="Consumer Discretionary", country="CH")
E("BIRK", "Birkenstock", "Birkenstock", domain="birkenstock.com", sector="Consumer Discretionary", country="DE")
E("TPR", "Tapestry", "Tapestry|Coach brand", domain="tapestry.com", sector="Consumer Discretionary")
E("CPRI", "Capri Holdings", "Capri Holdings|Michael Kors", domain="capriholdings.com", sector="Consumer Discretionary")
E("RL", "Ralph Lauren", "Ralph Lauren", domain="ralphlauren.com", sector="Consumer Discretionary")
E("VFC", "VF Corp", "VF Corp|VF Corporation", domain="vfc.com", sector="Consumer Discretionary")
E("ANF", "Abercrombie & Fitch", "Abercrombie", domain="abercrombie.com", sector="Consumer Discretionary")
E("AEO", "American Eagle Outfitters", "American Eagle", domain="ae.com", sector="Consumer Discretionary")
E("GAP", "Gap", "Gap Inc|Old Navy|?Gap", domain="gap.com", sector="Consumer Discretionary")
E("URBN", "Urban Outfitters", "Urban Outfitters", domain="urbn.com", sector="Consumer Discretionary")
E("FL", "Foot Locker", "Foot Locker", domain="footlocker.com", sector="Consumer Discretionary")
E("DKS", "Dick's Sporting Goods", "Dick's Sporting Goods|Dick's", domain="dicks.com", sector="Consumer Discretionary")
E("BBWI", "Bath & Body Works", "Bath & Body Works|L Brands", domain="bbwinc.com", sector="Consumer Discretionary")
E("VSCO", "Victoria's Secret", "Victoria's Secret", domain="victoriassecret.com", sector="Consumer Discretionary")
E("WSM", "Williams-Sonoma", "Williams-Sonoma|Williams Sonoma", domain="williams-sonoma.com", sector="Consumer Discretionary")
E("RH", "RH", "Restoration Hardware", domain="rh.com", sector="Consumer Discretionary")
E("SBUX", "Starbucks", "Starbucks", domain="starbucks.com", sector="Consumer Discretionary")
E("MCD", "McDonald's", "McDonald's|McDonalds", domain="mcdonalds.com", sector="Consumer Discretionary")
E("CMG", "Chipotle", "Chipotle", domain="chipotle.com", sector="Consumer Discretionary")
E("DPZ", "Domino's", "Domino's|Dominos", domain="dominos.com", sector="Consumer Discretionary")
E("YUM", "Yum! Brands", "Yum Brands|Yum! Brands|Taco Bell|KFC", domain="yum.com", sector="Consumer Discretionary")
E("WEN", "Wendy's", "Wendy's", domain="wendys.com", sector="Consumer Discretionary")
E("SHAK", "Shake Shack", "Shake Shack", domain="shakeshack.com", sector="Consumer Discretionary")
E("CAVA", "Cava", "Cava Group|Cava", domain="cava.com", sector="Consumer Discretionary")
E("SG", "Sweetgreen", "Sweetgreen", domain="sweetgreen.com", sector="Consumer Discretionary")
E("BROS", "Dutch Bros", "Dutch Bros", domain="dutchbros.com", sector="Consumer Discretionary")
E("DNUT", "Krispy Kreme", "Krispy Kreme", domain="krispykreme.com", sector="Consumer Discretionary")
E("DRI", "Darden Restaurants", "Darden|Olive Garden", domain="darden.com", sector="Consumer Discretionary")
E("KO", "Coca-Cola", "Coca-Cola|Coca Cola|Coke", domain="coca-colacompany.com", sector="Consumer Staples")
E("PEP", "PepsiCo", "PepsiCo|Pepsi|Frito-Lay", domain="pepsico.com", sector="Consumer Staples")
E("MNST", "Monster Beverage", "Monster Beverage", domain="monsterbevcorp.com", sector="Consumer Staples")
E("CELH", "Celsius Holdings", "Celsius Holdings|Celsius energy", domain="celsius.com", sector="Consumer Staples")
E("STZ", "Constellation Brands", "Constellation Brands|Corona beer|Modelo", domain="cbrands.com", sector="Consumer Staples")
E("BUD", "Anheuser-Busch InBev", "Anheuser-Busch|AB InBev|Bud Light|Budweiser", domain="ab-inbev.com", sector="Consumer Staples", country="BE")
E("TAP", "Molson Coors", "Molson Coors|Coors", domain="molsoncoors.com", sector="Consumer Staples")
E("SAM", "Boston Beer", "Boston Beer", domain="bostonbeer.com", sector="Consumer Staples")
E("MO", "Altria", "Altria", domain="altria.com", sector="Consumer Staples")
E("PM", "Philip Morris International", "Philip Morris", domain="pmi.com", sector="Consumer Staples")
E("PG", "Procter & Gamble", "Procter & Gamble|Procter and Gamble|P&G", domain="pg.com", sector="Consumer Staples")
E("CL", "Colgate-Palmolive", "Colgate", domain="colgatepalmolive.com", sector="Consumer Staples")
E("KMB", "Kimberly-Clark", "Kimberly-Clark|Kimberly Clark", domain="kimberly-clark.com", sector="Consumer Staples")
E("UL", "Unilever", "Unilever", domain="unilever.com", sector="Consumer Staples", country="UK")
E("KHC", "Kraft Heinz", "Kraft Heinz|Kraft", domain="kraftheinzcompany.com", sector="Consumer Staples")
E("GIS", "General Mills", "General Mills", domain="generalmills.com", sector="Consumer Staples")
E("K", "Kellanova (Kellogg)", "Kellogg|Kellanova|Kellogg's", domain="kellanova.com", sector="Consumer Staples")
E("CPB", "Campbell's", "Campbell Soup|Campbell's", domain="thecampbellscompany.com", sector="Consumer Staples")
E("TSN", "Tyson Foods", "Tyson Foods", domain="tysonfoods.com", sector="Consumer Staples")
E("HSY", "Hershey", "Hershey|Hershey's", domain="thehersheycompany.com", sector="Consumer Staples")
E("MDLZ", "Mondelez", "Mondelez|Mondelēz|Oreo", domain="mondelezinternational.com", sector="Consumer Staples")
E("CLX", "Clorox", "Clorox", domain="thecloroxcompany.com", sector="Consumer Staples")
E("CHD", "Church & Dwight", "Church & Dwight", domain="churchdwight.com", sector="Consumer Staples")
E("BYND", "Beyond Meat", "Beyond Meat", domain="beyondmeat.com", sector="Consumer Staples")
E("OTLY", "Oatly", "Oatly", domain="oatly.com", sector="Consumer Staples", country="SE")
E("SFM", "Sprouts Farmers Market", "Sprouts Farmers", domain="sprouts.com", sector="Consumer Staples")
E("WBA", "Walgreens Boots Alliance", "Walgreens", domain="walgreens.com", sector="Consumer Staples", delisted="2025-08-28")
E("CVS", "CVS Health", "CVS|CVS Health|Aetna", domain="cvshealth.com", sector="Health Care")
E("MAT", "Mattel", "Mattel|Barbie maker", domain="mattel.com", sector="Consumer Discretionary")
E("HAS", "Hasbro", "Hasbro", domain="hasbro.com", sector="Consumer Discretionary")
E("PLAY", "Dave & Buster's", "Dave & Buster's", domain="daveandbusters.com", sector="Consumer Discretionary")
E("SIX", "Six Flags", "Six Flags", domain="sixflags.com", sector="Consumer Discretionary")
E("FUN", "Cedar Fair", "Cedar Fair", domain="cedarfair.com", sector="Consumer Discretionary")

# --- Travel / leisure --------------------------------------------------------
E("DAL", "Delta Air Lines", "Delta Air Lines|Delta Airlines|Delta Air|?Delta", domain="delta.com", sector="Industrials")
E("UAL", "United Airlines", "United Airlines|United Air Lines", domain="united.com", sector="Industrials")
E("AAL", "American Airlines", "American Airlines", domain="aa.com", sector="Industrials")
E("LUV", "Southwest Airlines", "Southwest Airlines|?Southwest", domain="southwest.com", sector="Industrials")
E("JBLU", "JetBlue", "JetBlue", domain="jetblue.com", sector="Industrials")
E("ALK", "Alaska Air", "Alaska Air|Alaska Airlines", domain="alaskaair.com", sector="Industrials")
E("SAVE", "Spirit Airlines", "Spirit Airlines", domain="spirit.com", sector="Industrials", delisted="2025-08-19")
E("CCL", "Carnival", "Carnival Corp|Carnival Cruise|?Carnival", domain="carnivalcorp.com", sector="Consumer Discretionary")
E("RCL", "Royal Caribbean", "Royal Caribbean", domain="royalcaribbean.com", sector="Consumer Discretionary")
E("NCLH", "Norwegian Cruise Line", "Norwegian Cruise", domain="ncl.com", sector="Consumer Discretionary")
E("MAR", "Marriott", "Marriott", domain="marriott.com", sector="Consumer Discretionary")
E("HLT", "Hilton", "Hilton", domain="hilton.com", sector="Consumer Discretionary")
E("H", "Hyatt", "Hyatt", domain="hyatt.com", sector="Consumer Discretionary")
E("EXPE", "Expedia", "Expedia", domain="expediagroup.com", sector="Consumer Discretionary")
E("BKNG", "Booking Holdings", "Booking Holdings|Booking.com|Priceline", domain="bookingholdings.com", sector="Consumer Discretionary")
E("TRIP", "Tripadvisor", "Tripadvisor|TripAdvisor", domain="tripadvisor.com", sector="Communication Services")
E("LVS", "Las Vegas Sands", "Las Vegas Sands", domain="sands.com", sector="Consumer Discretionary")
E("WYNN", "Wynn Resorts", "Wynn Resorts|Wynn", domain="wynnresorts.com", sector="Consumer Discretionary")
E("MGM", "MGM Resorts", "MGM Resorts|MGM", domain="mgmresorts.com", sector="Consumer Discretionary")
E("CZR", "Caesars Entertainment", "Caesars", domain="caesars.com", sector="Consumer Discretionary")
E("DKNG", "DraftKings", "DraftKings|Draftkings", domain="draftkings.com", sector="Consumer Discretionary")
E("PENN", "Penn Entertainment", "Penn National|Penn Entertainment", domain="pennentertainment.com", sector="Consumer Discretionary")
E("LYV", "Live Nation", "Live Nation|Ticketmaster", domain="livenationentertainment.com", sector="Communication Services")
E("BA", "Boeing", "Boeing|Boeing's", domain="boeing.com", sector="Industrials")
E("EADSY", "Airbus", "Airbus", domain="airbus.com", sector="Industrials", country="FR")
E("SPR", "Spirit AeroSystems", "Spirit AeroSystems|Spirit Aero", domain="spiritaero.com", sector="Industrials")

# --- Media / telecom ---------------------------------------------------------
E("DIS", "Disney", "Disney|Disney's|Walt Disney|Disney+|ESPN", domain="thewaltdisneycompany.com", sector="Communication Services")
E("CMCSA", "Comcast", "Comcast|NBCUniversal|Peacock streaming|CNBC<2026-01-01|NBC News|MSNBC<2026-01-01", domain="comcastcorporation.com", sector="Communication Services")
E("CHTR", "Charter Communications", "Charter Communications", domain="charter.com", sector="Communication Services")
E("WBD", "Warner Bros. Discovery", "Warner Bros. Discovery|Warner Bros Discovery|Warner Brothers Discovery|HBO Max|Discovery Inc", domain="wbd.com", sector="Communication Services")
E("PARA", "Paramount Global", "Paramount Global|Paramount|ViacomCBS", domain="paramount.com", sector="Communication Services", yf="PSKY")
E("FOXA", "Fox Corp", "Fox Corp|Fox Corporation|Fox News|Fox Business", domain="foxcorporation.com", sector="Communication Services")
E("NWSA", "News Corp", "News Corp|Wall Street Journal|Barron's|MarketWatch|Dow Jones Newswires", domain="newscorp.com", sector="Communication Services")
E("NYT", "New York Times", "New York Times Company|New York Times|NYT Co", domain="nytco.com", sector="Communication Services")
E("LGF-A", "Lionsgate", "Lionsgate", domain="lionsgate.com", sector="Communication Services", yf="LION")
E("VZ", "Verizon", "Verizon", domain="verizon.com", sector="Communication Services")
E("T", "AT&T|AT and T|AT & T", "AT&T|AT and T|AT & T", domain="att.com", sector="Communication Services")
E("TMUS", "T-Mobile|T Mobile", "T-Mobile|T Mobile", domain="t-mobile.com", sector="Communication Services")
E("SIRI", "Sirius XM", "Sirius XM|SiriusXM", domain="siriusxm.com", sector="Communication Services")
E("IAC", "IAC", "IAC Inc|Dotdash Meredith", domain="iac.com", sector="Communication Services")
E("SONY", "Sony", "Sony", domain="sony.com", sector="Consumer Discretionary", country="JP")
E("NTDOY", "Nintendo", "Nintendo", domain="nintendo.com", sector="Communication Services", country="JP")

# --- Health care -------------------------------------------------------------
E("PFE", "Pfizer", "Pfizer|Pfizer's", domain="pfizer.com", sector="Health Care")
E("MRNA", "Moderna", "Moderna", domain="modernatx.com", sector="Health Care")
E("BNTX", "BioNTech", "BioNTech", domain="biontech.de", sector="Health Care", country="DE")
E("NVAX", "Novavax", "Novavax", domain="novavax.com", sector="Health Care")
E("JNJ", "Johnson & Johnson", "Johnson & Johnson|Johnson and Johnson|J&J", domain="jnj.com", sector="Health Care")
E("MRK", "Merck", "Merck", domain="merck.com", sector="Health Care")
E("LLY", "Eli Lilly", "Eli Lilly|Lilly's|?Lilly|Zepbound|Mounjaro", domain="lilly.com", sector="Health Care")
E("NVO", "Novo Nordisk", "Novo Nordisk|Ozempic|Wegovy", domain="novonordisk.com", sector="Health Care", country="DK")
E("ABBV", "AbbVie", "AbbVie|Abbvie", domain="abbvie.com", sector="Health Care")
E("AMGN", "Amgen", "Amgen", domain="amgen.com", sector="Health Care")
E("GILD", "Gilead Sciences", "Gilead", domain="gilead.com", sector="Health Care")
E("REGN", "Regeneron", "Regeneron", domain="regeneron.com", sector="Health Care")
E("VRTX", "Vertex Pharmaceuticals", "Vertex Pharmaceuticals", domain="vrtx.com", sector="Health Care")
E("BIIB", "Biogen", "Biogen", domain="biogen.com", sector="Health Care")
E("BMY", "Bristol Myers Squibb", "Bristol Myers|Bristol-Myers", domain="bms.com", sector="Health Care")
E("ABT", "Abbott Laboratories", "Abbott Labs|Abbott Laboratories|Abbott", domain="abbott.com", sector="Health Care")
E("TMO", "Thermo Fisher Scientific", "Thermo Fisher", domain="thermofisher.com", sector="Health Care")
E("DHR", "Danaher", "Danaher", domain="danaher.com", sector="Health Care")
E("MDT", "Medtronic", "Medtronic", domain="medtronic.com", sector="Health Care")
E("ISRG", "Intuitive Surgical", "Intuitive Surgical", domain="intuitive.com", sector="Health Care")
E("SYK", "Stryker", "Stryker", domain="stryker.com", sector="Health Care")
E("BSX", "Boston Scientific", "Boston Scientific", domain="bostonscientific.com", sector="Health Care")
E("DXCM", "Dexcom", "Dexcom", domain="dexcom.com", sector="Health Care")
E("ILMN", "Illumina", "Illumina", domain="illumina.com", sector="Health Care")
E("UNH", "UnitedHealth Group", "UnitedHealth|United Health|United HealthCare|UnitedHealthcare", domain="unitedhealthgroup.com", sector="Health Care")
E("CI", "Cigna", "Cigna", domain="cigna.com", sector="Health Care")
E("HUM", "Humana", "Humana", domain="humana.com", sector="Health Care")
E("ELV", "Elevance Health", "Elevance|Anthem Inc", domain="elevancehealth.com", sector="Health Care")
E("CNC", "Centene", "Centene", domain="centene.com", sector="Health Care")
E("HCA", "HCA Healthcare", "HCA Healthcare|HCA", domain="hcahealthcare.com", sector="Health Care")
E("TDOC", "Teladoc Health", "Teladoc", domain="teladochealth.com", sector="Health Care")
E("HIMS", "Hims & Hers", "Hims & Hers|Hims and Hers", domain="hims.com", sector="Health Care")
E("OSCR", "Oscar Health", "Oscar Health", domain="hioscar.com", sector="Health Care")
E("ME", "23andMe", "23andMe", domain="23andme.com", sector="Health Care", delisted="2025-03-31")
E("TEVA", "Teva", "Teva", domain="tevapharm.com", sector="Health Care", country="IL")
E("ZTS", "Zoetis", "Zoetis", domain="zoetis.com", sector="Health Care")
E("MCK", "McKesson", "McKesson", domain="mckesson.com", sector="Health Care")
E("ALGN", "Align Technology", "Align Technology|Invisalign", domain="aligntech.com", sector="Health Care")

# --- Financials --------------------------------------------------------------
E("JPM", "JPMorgan Chase", "JPMorgan|JP Morgan|J.P. Morgan|JPMorgan Chase|Chase Bank", domain="jpmorganchase.com", sector="Financials")
E("GS", "Goldman Sachs", "Goldman Sachs|Goldman", domain="goldmansachs.com", sector="Financials")
E("MS", "Morgan Stanley", "Morgan Stanley", domain="morganstanley.com", sector="Financials")
E("BAC", "Bank of America", "Bank of America|BofA|Merrill Lynch", domain="bankofamerica.com", sector="Financials")
E("WFC", "Wells Fargo", "Wells Fargo", domain="wellsfargo.com", sector="Financials")
E("C", "Citigroup", "Citigroup|Citi Group|Citibank|Citi|?City Group", domain="citigroup.com", sector="Financials")
E("USB", "U.S. Bancorp", "U.S. Bancorp|US Bancorp|U.S. Bank", domain="usbank.com", sector="Financials")
E("PNC", "PNC Financial", "PNC", domain="pnc.com", sector="Financials")
E("TFC", "Truist", "Truist", domain="truist.com", sector="Financials")
E("FITB", "Fifth Third Bancorp", "Fifth Third", domain="53.com", sector="Financials")
E("KEY", "KeyCorp", "KeyCorp|KeyBank", domain="key.com", sector="Financials")
E("RF", "Regions Financial", "Regions Financial|Regions Bank", domain="regions.com", sector="Financials")
E("HBAN", "Huntington Bancshares", "Huntington Bancshares|Huntington Bank", domain="huntington.com", sector="Financials")
E("MTB", "M&T Bank", "M&T Bank", domain="mtb.com", sector="Financials")
E("CFG", "Citizens Financial", "Citizens Financial|Citizens Bank", domain="citizensbank.com", sector="Financials")
E("FRC", "First Republic Bank", "First Republic", domain="firstrepublic.com", sector="Financials", delisted="2023-05-01")
E("SIVB", "SVB Financial (Silicon Valley Bank)", "Silicon Valley Bank|SVB", domain="svb.com", sector="Financials", delisted="2023-03-10")
E("SBNY", "Signature Bank", "Signature Bank", domain="signatureny.com", sector="Financials", delisted="2023-03-12")
E("PACW", "PacWest Bancorp", "PacWest", domain="pacwest.com", sector="Financials", delisted="2023-11-30")
E("WAL", "Western Alliance", "Western Alliance", domain="westernalliancebancorporation.com", sector="Financials")
E("NYCB", "New York Community Bancorp (Flagstar)", "New York Community Bancorp|New York Community Bank|Flagstar", domain="flagstar.com", sector="Financials", yf="FLG")
E("CS", "Credit Suisse", "Credit Suisse", domain="credit-suisse.com", sector="Financials", country="CH", delisted="2023-06-12")
E("UBS", "UBS", "UBS", domain="ubs.com", sector="Financials", country="CH")
E("DB", "Deutsche Bank", "Deutsche Bank", domain="db.com", sector="Financials", country="DE")
E("BCS", "Barclays", "Barclays", domain="barclays.com", sector="Financials", country="UK")
E("HSBC", "HSBC", "HSBC", domain="hsbc.com", sector="Financials", country="UK")
E("COF", "Capital One", "Capital One", domain="capitalone.com", sector="Financials")
E("DFS", "Discover Financial", "Discover Financial|Discover card", domain="discover.com", sector="Financials", delisted="2025-05-19")
E("SYF", "Synchrony", "Synchrony", domain="synchrony.com", sector="Financials")
E("ALLY", "Ally Financial", "Ally Financial|Ally Invest|Ally Bank", domain="ally.com", sector="Financials")
E("AXP", "American Express", "American Express|AmEx|Amex", domain="americanexpress.com", sector="Financials")
E("V", "Visa", "Visa Inc|?Visa", domain="visa.com", sector="Financials")
E("MA", "Mastercard", "Mastercard|MasterCard|Master Card", domain="mastercard.com", sector="Financials")
E("SCHW", "Charles Schwab", "Charles Schwab|Schwab|Schwab's", domain="schwab.com", sector="Financials")
E("IBKR", "Interactive Brokers", "Interactive Brokers", domain="interactivebrokers.com", sector="Financials")
E("LPLA", "LPL Financial", "LPL Financial|LPL Research|LPL", domain="lpl.com", sector="Financials")
E("RJF", "Raymond James", "Raymond James", domain="raymondjames.com", sector="Financials")
E("BLK", "BlackRock", "BlackRock|Blackrock|Black Rock|iShares", domain="blackrock.com", sector="Financials")
E("BX", "Blackstone|?Black Stone", "Blackstone|?Black Stone", domain="blackstone.com", sector="Financials")
E("KKR", "KKR", "KKR", domain="kkr.com", sector="Financials")
E("APO", "Apollo Global Management", "Apollo Global|Apollo Global Management|?Apollo", domain="apollo.com", sector="Financials")
E("CG", "Carlyle Group", "Carlyle", domain="carlyle.com", sector="Financials")
E("ARES", "Ares Management", "Ares Management|Ares Capital", domain="aresmgmt.com", sector="Financials")
E("OWL", "Blue Owl Capital", "Blue Owl", domain="blueowl.com", sector="Financials")
E("STT", "State Street", "State Street", domain="statestreet.com", sector="Financials")
E("BK", "BNY (Bank of New York Mellon)", "BNY Mellon|Bank of New York Mellon|BNY", domain="bny.com", sector="Financials", yf="BNY")
E("NTRS", "Northern Trust", "Northern Trust", domain="northerntrust.com", sector="Financials")
E("IVZ", "Invesco", "Invesco", domain="invesco.com", sector="Financials")
E("TROW", "T. Rowe Price", "T. Rowe Price|T Rowe Price", domain="troweprice.com", sector="Financials")
E("BEN", "Franklin Templeton", "Franklin Templeton|Franklin Resources", domain="franklintempleton.com", sector="Financials")
E("AMP", "Ameriprise", "Ameriprise", domain="ameriprise.com", sector="Financials")
E("NDAQ", "Nasdaq Inc.", "Nasdaq Inc|Nasdaq, Inc", domain="nasdaq.com", sector="Financials")
E("ICE", "Intercontinental Exchange", "Intercontinental Exchange", domain="ice.com", sector="Financials")
E("CME", "CME Group", "CME Group|CME", domain="cmegroup.com", sector="Financials")
E("CBOE", "Cboe Global Markets", "Cboe|CBOE", domain="cboe.com", sector="Financials")
E("SPGI", "S&P Global", "S&P Global", domain="spglobal.com", sector="Financials")
E("MCO", "Moody's", "Moody's|Moodys", domain="moodys.com", sector="Financials")
E("MSCI", "MSCI", "MSCI", domain="msci.com", sector="Financials")
E("FDS", "FactSet", "FactSet", domain="factset.com", sector="Financials")
E("MORN", "Morningstar", "Morningstar", domain="morningstar.com", sector="Financials")
E("MMC", "Marsh McLennan", "Marsh McLennan|Marsh & McLennan", domain="marshmclennan.com", sector="Financials")
E("AON", "Aon", "Aon", domain="aon.com", sector="Financials")
E("AIG", "AIG", "AIG", domain="aig.com", sector="Financials")
E("MET", "MetLife", "MetLife", domain="metlife.com", sector="Financials")
E("PRU", "Prudential Financial", "Prudential", domain="prudential.com", sector="Financials")
E("ALL", "Allstate", "Allstate", domain="allstate.com", sector="Financials")
E("PGR", "Progressive", "Progressive Corp|Progressive Insurance|?Progressive", domain="progressive.com", sector="Financials")
E("TRV", "Travelers", "Travelers Companies|?Travelers", domain="travelers.com", sector="Financials")
E("CB", "Chubb", "Chubb", domain="chubb.com", sector="Financials")
E("HIG", "Hartford", "Hartford Financial|The Hartford", domain="thehartford.com", sector="Financials")
E("BRK-B", "Berkshire Hathaway", "Berkshire Hathaway|Berkshire|Berkshire's|Berkshire Hathaway's", domain="berkshirehathaway.com", sector="Financials", yf="BRK-B")
E("MKL", "Markel", "Markel", domain="markel.com", sector="Financials")
E("LMND", "Lemonade", "Lemonade Inc|?Lemonade", domain="lemonade.com", sector="Financials")
E("RKT", "Rocket Companies", "Rocket Companies|Rocket Mortgage", domain="rocketcompanies.com", sector="Financials")
E("UWMC", "UWM Holdings", "UWM Holdings|United Wholesale Mortgage", domain="uwm.com", sector="Financials")
E("FRHC", "Freedom Holding", "Freedom Holding|Freedom Capital Markets", domain="freedomholdingcorp.com", sector="Financials")
E("VIRT", "Virtu Financial", "Virtu", domain="virtu.com", sector="Financials")
E("ETOR", "eToro", "eToro|Etoro", domain="etoro.com", sector="Financials", country="IL")
E("ALIZY", "Allianz", "Allianz", domain="allianz.com", sector="Financials", country="DE")
E("AMTD", "TD Ameritrade", "TD Ameritrade", domain="tdameritrade.com", sector="Financials", delisted="2020-10-06")
E("BRK-A", "Berkshire Hathaway (Class A)", "", domain="berkshirehathaway.com", sector="Financials", yf="BRK-A")
E("MUFG", "Mitsubishi UFJ", "Mitsubishi UFJ|MUFG", domain="mufg.jp", sector="Financials", country="JP")
E("SFTBY", "SoftBank", "SoftBank|Softbank", domain="softbank.jp", sector="Financials", country="JP")
E("JEF", "Jefferies", "Jefferies", domain="jefferies.com", sector="Financials")
E("LAZ", "Lazard", "Lazard", domain="lazard.com", sector="Financials")
E("EVR", "Evercore", "Evercore", domain="evercore.com", sector="Financials")

# --- Industrials / transport / defense ---------------------------------------
E("GE", "GE Aerospace", "General Electric|GE Aerospace|?GE", domain="geaerospace.com", sector="Industrials")
E("GEV", "GE Vernova", "GE Vernova", domain="gevernova.com", sector="Industrials")
E("GEHC", "GE HealthCare", "GE HealthCare|GE Healthcare", domain="gehealthcare.com", sector="Health Care")
E("HON", "Honeywell", "Honeywell", domain="honeywell.com", sector="Industrials")
E("MMM", "3M", "3M", domain="3m.com", sector="Industrials")
E("CAT", "Caterpillar", "Caterpillar", domain="caterpillar.com", sector="Industrials")
E("DE", "Deere & Company", "Deere|John Deere", domain="deere.com", sector="Industrials")
E("LMT", "Lockheed Martin", "Lockheed Martin|Lockheed", domain="lockheedmartin.com", sector="Industrials")
E("RTX", "RTX (Raytheon)", "Raytheon|RTX Corp", domain="rtx.com", sector="Industrials")
E("NOC", "Northrop Grumman", "Northrop Grumman|Northrop", domain="northropgrumman.com", sector="Industrials")
E("GD", "General Dynamics", "General Dynamics", domain="gd.com", sector="Industrials")
E("LHX", "L3Harris", "L3Harris", domain="l3harris.com", sector="Industrials")
E("TDG", "TransDigm", "TransDigm", domain="transdigm.com", sector="Industrials")
E("HWM", "Howmet Aerospace", "Howmet", domain="howmet.com", sector="Industrials")
E("RKLB", "Rocket Lab", "Rocket Lab", domain="rocketlabusa.com", sector="Industrials")
E("SPCX", "SpaceX", "SpaceX|Space X|Starlink", domain="spacex.com", sector="Industrials")
E("ASTS", "AST SpaceMobile", "AST SpaceMobile", domain="ast-science.com", sector="Communication Services")
E("UPS", "UPS", "UPS|United Parcel Service", domain="ups.com", sector="Industrials")
E("FDX", "FedEx", "FedEx|Fedex", domain="fedex.com", sector="Industrials")
E("UNP", "Union Pacific", "Union Pacific", domain="up.com", sector="Industrials")
E("CSX", "CSX", "CSX", domain="csx.com", sector="Industrials")
E("NSC", "Norfolk Southern", "Norfolk Southern", domain="norfolksouthern.com", sector="Industrials")
E("JBHT", "J.B. Hunt", "J.B. Hunt|JB Hunt", domain="jbhunt.com", sector="Industrials")
E("ODFL", "Old Dominion Freight Line", "Old Dominion", domain="odfl.com", sector="Industrials")
E("XPO", "XPO", "XPO Logistics|XPO", domain="xpo.com", sector="Industrials")
E("WM", "Waste Management", "Waste Management", domain="wm.com", sector="Industrials")
E("EMR", "Emerson Electric", "Emerson Electric|Emerson", domain="emerson.com", sector="Industrials")
E("ETN", "Eaton", "Eaton", domain="eaton.com", sector="Industrials")
E("ITW", "Illinois Tool Works", "Illinois Tool Works", domain="itw.com", sector="Industrials")
E("PH", "Parker-Hannifin", "Parker-Hannifin|Parker Hannifin", domain="parker.com", sector="Industrials")
E("ROK", "Rockwell Automation", "Rockwell Automation", domain="rockwellautomation.com", sector="Industrials")
E("CMI", "Cummins", "Cummins", domain="cummins.com", sector="Industrials")
E("PCAR", "PACCAR", "PACCAR|Paccar", domain="paccar.com", sector="Industrials")
E("TT", "Trane Technologies", "Trane", domain="tranetechnologies.com", sector="Industrials")
E("CARR", "Carrier Global", "Carrier Global", domain="carrier.com", sector="Industrials")
E("JCI", "Johnson Controls", "Johnson Controls", domain="johnsoncontrols.com", sector="Industrials")
E("URI", "United Rentals", "United Rentals", domain="unitedrentals.com", sector="Industrials")
E("VRT", "Vertiv", "Vertiv", domain="vertiv.com", sector="Industrials")
E("ADP", "ADP", "Automatic Data Processing|ADP", domain="adp.com", sector="Industrials")
E("PAYX", "Paychex", "Paychex", domain="paychex.com", sector="Industrials")
E("WE", "WeWork", "WeWork", domain="wework.com", sector="Real Estate", delisted="2023-11-07")
E("LEN", "Lennar", "Lennar", domain="lennar.com", sector="Consumer Discretionary")
E("DHI", "D.R. Horton", "D.R. Horton|DR Horton", domain="drhorton.com", sector="Consumer Discretionary")
E("PHM", "PulteGroup", "PulteGroup|Pulte", domain="pultegroup.com", sector="Consumer Discretionary")
E("TOL", "Toll Brothers", "Toll Brothers", domain="tollbrothers.com", sector="Consumer Discretionary")
E("KBH", "KB Home", "KB Home", domain="kbhome.com", sector="Consumer Discretionary")
E("NVR", "NVR", "NVR Inc", domain="nvrinc.com", sector="Consumer Discretionary")
E("BLDR", "Builders FirstSource", "Builders FirstSource", domain="bldr.com", sector="Industrials")
E("FND", "Floor & Decor", "Floor & Decor", domain="flooranddecor.com", sector="Consumer Discretionary")

# --- Energy / materials / utilities ------------------------------------------
E("XOM", "ExxonMobil", "ExxonMobil|Exxon Mobil|Exxon", domain="exxonmobil.com", sector="Energy")
E("CVX", "Chevron", "Chevron", domain="chevron.com", sector="Energy")
E("COP", "ConocoPhillips", "ConocoPhillips|Conoco", domain="conocophillips.com", sector="Energy")
E("OXY", "Occidental Petroleum", "Occidental", domain="oxy.com", sector="Energy")
E("DVN", "Devon Energy", "Devon Energy", domain="devonenergy.com", sector="Energy")
E("PXD", "Pioneer Natural Resources", "Pioneer Natural Resources", domain="pxd.com", sector="Energy", delisted="2024-05-03")
E("FANG", "Diamondback Energy", "Diamondback", domain="diamondbackenergy.com", sector="Energy")
E("EOG", "EOG Resources", "EOG Resources|EOG", domain="eogresources.com", sector="Energy")
E("MRO", "Marathon Oil", "Marathon Oil", domain="marathonoil.com", sector="Energy", delisted="2024-11-22")
E("MPC", "Marathon Petroleum", "Marathon Petroleum", domain="marathonpetroleum.com", sector="Energy")
E("VLO", "Valero", "Valero", domain="valero.com", sector="Energy")
E("PSX", "Phillips 66", "Phillips 66", domain="phillips66.com", sector="Energy")
E("HAL", "Halliburton", "Halliburton", domain="halliburton.com", sector="Energy")
E("SLB", "SLB (Schlumberger)", "Schlumberger|SLB", domain="slb.com", sector="Energy")
E("BKR", "Baker Hughes", "Baker Hughes", domain="bakerhughes.com", sector="Energy")
E("KMI", "Kinder Morgan", "Kinder Morgan", domain="kindermorgan.com", sector="Energy")
E("LNG", "Cheniere Energy", "Cheniere", domain="cheniere.com", sector="Energy")
E("SHEL", "Shell", "Royal Dutch Shell|Shell plc|?Shell", domain="shell.com", sector="Energy", country="UK")
E("BP", "BP", "BP plc|?BP", domain="bp.com", sector="Energy", country="UK")
E("TTE", "TotalEnergies", "TotalEnergies|Total SA", domain="totalenergies.com", sector="Energy", country="FR")
E("2222.SR", "Saudi Aramco", "Saudi Aramco|Aramco", domain="aramco.com", sector="Energy", country="SA")
E("PBR", "Petrobras", "Petrobras", domain="petrobras.com.br", sector="Energy", country="BR")
E("NEE", "NextEra Energy", "NextEra", domain="nexteraenergy.com", sector="Utilities")
E("DUK", "Duke Energy", "Duke Energy", domain="duke-energy.com", sector="Utilities")
E("SO", "Southern Company", "Southern Company|Southern Co", domain="southerncompany.com", sector="Utilities")
E("D", "Dominion Energy", "Dominion Energy", domain="dominionenergy.com", sector="Utilities")
E("CEG", "Constellation Energy", "Constellation Energy", domain="constellationenergy.com", sector="Utilities")
E("VST", "Vistra", "Vistra", domain="vistra.com", sector="Utilities")
E("PCG", "PG&E", "PG&E|Pacific Gas", domain="pge.com", sector="Utilities")
E("OKLO", "Oklo", "Oklo", domain="oklo.com", sector="Utilities")
E("SMR", "NuScale Power", "NuScale", domain="nuscalepower.com", sector="Industrials")
E("ENPH", "Enphase Energy", "Enphase", domain="enphase.com", sector="Technology")
E("FSLR", "First Solar", "First Solar", domain="firstsolar.com", sector="Technology")
E("RUN", "Sunrun", "Sunrun", domain="sunrun.com", sector="Industrials")
E("SEDG", "SolarEdge", "SolarEdge", domain="solaredge.com", sector="Technology")
E("SPWR", "SunPower", "SunPower", domain="sunpower.com", sector="Technology", delisted="2024-08-12")
E("FCX", "Freeport-McMoRan", "Freeport-McMoRan|Freeport McMoRan|Freeport", domain="fcx.com", sector="Materials")
E("NEM", "Newmont", "Newmont", domain="newmont.com", sector="Materials")
E("GOLD", "Barrick Gold", "Barrick", domain="barrick.com", sector="Materials", country="CA", yf="B")
E("AA", "Alcoa", "Alcoa", domain="alcoa.com", sector="Materials")
E("NUE", "Nucor", "Nucor", domain="nucor.com", sector="Materials")
E("X", "U.S. Steel", "U.S. Steel|US Steel|United States Steel", domain="ussteel.com", sector="Materials", delisted="2025-06-18")
E("CLF", "Cleveland-Cliffs", "Cleveland-Cliffs", domain="clevelandcliffs.com", sector="Materials")
E("DOW", "Dow Inc.", "Dow Inc|Dow Chemical", domain="dow.com", sector="Materials")
E("DD", "DuPont", "DuPont", domain="dupont.com", sector="Materials")
E("LIN", "Linde", "Linde", domain="linde.com", sector="Materials", country="UK")
E("APD", "Air Products", "Air Products", domain="airproducts.com", sector="Materials")
E("SHW", "Sherwin-Williams", "Sherwin-Williams|Sherwin Williams", domain="sherwin-williams.com", sector="Materials")
E("ALB", "Albemarle", "Albemarle", domain="albemarle.com", sector="Materials")
E("MP", "MP Materials", "MP Materials", domain="mpmaterials.com", sector="Materials")
E("VALE", "Vale", "Vale SA", domain="vale.com", sector="Materials", country="BR")
E("RIO", "Rio Tinto", "Rio Tinto", domain="riotinto.com", sector="Materials", country="UK")
E("BHP", "BHP", "BHP", domain="bhp.com", sector="Materials", country="AU")

# --- International bellwethers -----------------------------------------------
E("RELIANCE.NS", "Reliance Industries", "Reliance Industries|Reliance Jio|Jio Platforms", domain="ril.com", sector="Energy", country="IN")
E("005930.KS", "Samsung Electronics", "Samsung", domain="samsung.com", sector="Technology", country="KR")
E("MC.PA", "LVMH", "LVMH|Louis Vuitton", domain="lvmh.com", sector="Consumer Discretionary", country="FR")
E("NSRGY", "Nestlé", "Nestle|Nestlé", domain="nestle.com", sector="Consumer Staples", country="CH")
E("VWAGY", "Volkswagen", "Volkswagen", domain="volkswagen.com", sector="Consumer Discretionary", country="DE")
E("BMWYY", "BMW", "BMW", domain="bmw.com", sector="Consumer Discretionary", country="DE")
E("MBGYY", "Mercedes-Benz Group", "Mercedes-Benz|Mercedes|Daimler", domain="mercedes-benz.com", sector="Consumer Discretionary", country="DE")
E("ADDYY", "Adidas", "Adidas", domain="adidas.com", sector="Consumer Discretionary", country="DE")
E("INFY", "Infosys", "Infosys", domain="infosys.com", sector="Technology", country="IN")
E("TCS.NS", "Tata Consultancy Services", "Tata Consultancy", domain="tcs.com", sector="Technology", country="IN")
E("ZOMATO.NS", "Eternal (Zomato)", "Zomato", domain="zomato.com", sector="Consumer Discretionary", country="IN")
E("PAYTM.NS", "Paytm", "Paytm", domain="paytm.com", sector="Financials", country="IN")
E("7203.T", "Toyota (Tokyo)", "", domain="toyota.com", sector="Consumer Discretionary", country="JP")
E("9984.T", "SoftBank Group (Tokyo)", "", domain="softbank.jp", sector="Financials", country="JP")
E("0700.HK", "Tencent (HK)", "", domain="tencent.com", sector="Communication Services", country="CN")
E("SHOP.TO", "Shopify (TSX)", "", domain="shopify.com", sector="Technology", country="CA")
E("ARM.L", "Arm (London)", "", domain="arm.com", sector="Technology", country="UK")
E("ABNB.X", "placeholder", "", domain="")

# --- Funds and index proxies that the show discusses as investments ----------
E("SPY", "SPDR S&P 500 ETF", "SPY|SPDR S&P 500", domain="ssga.com", sector="ETF", etf=True)
E("QQQ", "Invesco QQQ", "QQQ|Invesco QQQ", domain="invesco.com", sector="ETF", etf=True)
E("IWM", "iShares Russell 2000 ETF", "IWM|Russell 2000 ETF", domain="ishares.com", sector="ETF", etf=True)
E("DIA", "SPDR Dow Jones ETF", "DIA ETF", domain="ssga.com", sector="ETF", etf=True)
E("ARKK", "ARK Innovation ETF", "ARKK|ARK Innovation|ARK Invest|Ark Invest|ARK ETF", domain="ark-funds.com", sector="ETF", etf=True)
E("GLD", "SPDR Gold Shares", "GLD|SPDR Gold", domain="ssga.com", sector="ETF", etf=True)
E("TLT", "iShares 20+ Year Treasury ETF", "TLT", domain="ishares.com", sector="ETF", etf=True)
E("IBIT", "iShares Bitcoin Trust", "IBIT|iShares Bitcoin", domain="ishares.com", sector="ETF", etf=True)
E("GBTC", "Grayscale Bitcoin Trust", "GBTC|Grayscale Bitcoin Trust|Grayscale", domain="grayscale.com", sector="ETF", etf=True)
E("BITO", "ProShares Bitcoin ETF", "BITO", domain="proshares.com", sector="ETF", etf=True)
E("VOO", "Vanguard S&P 500 ETF", "VOO", domain="vanguard.com", sector="ETF", etf=True)
E("VTI", "Vanguard Total Stock Market ETF", "VTI", domain="vanguard.com", sector="ETF", etf=True)


# --- Added after reviewing Whisper transcripts and 2020-2026 market themes ---
E("VSNT", "Versant (CNBC, MSNBC)", "Versant|CNBC@2026-01-01|MSNBC@2026-01-01|MS NOW", domain="versant.com", sector="Communication Services")
E("BB", "BlackBerry", "BlackBerry|Blackberry", domain="blackberry.com", sector="Technology", country="CA")
E("NOK", "Nokia", "Nokia", domain="nokia.com", sector="Technology", country="FI")
E("SPCE", "Virgin Galactic", "Virgin Galactic", domain="virgingalactic.com", sector="Industrials")
E("TLRY", "Tilray", "Tilray", domain="tilray.com", sector="Health Care")
E("CGC", "Canopy Growth", "Canopy Growth", domain="canopygrowth.com", sector="Health Care", country="CA")
E("ACB", "Aurora Cannabis", "Aurora Cannabis", domain="auroramj.com", sector="Health Care", country="CA")
E("CLOV", "Clover Health", "Clover Health", domain="cloverhealth.com", sector="Health Care")
E("KLAR", "Klarna", "Klarna", domain="klarna.com", sector="Financials", country="SE")
E("CHYM", "Chime", "Chime Financial|?Chime", domain="chime.com", sector="Financials")
E("CRWV", "CoreWeave", "CoreWeave|Core Weave", domain="coreweave.com", sector="Technology")
E("NBIS", "Nebius", "Nebius", domain="nebius.com", sector="Technology", country="NL")
E("FIG", "Figma", "Figma", domain="figma.com", sector="Technology")
E("KVYO", "Klaviyo", "Klaviyo", domain="klaviyo.com", sector="Technology")
E("KVUE", "Kenvue", "Kenvue|Tylenol maker", domain="kenvue.com", sector="Consumer Staples")
E("WDC", "Western Digital", "Western Digital", domain="westerndigital.com", sector="Technology")
E("STX", "Seagate", "Seagate", domain="seagate.com", sector="Technology")
E("SNDK", "Sandisk", "Sandisk|SanDisk", domain="sandisk.com", sector="Technology")
E("XIACY", "Xiaomi", "Xiaomi", domain="mi.com", sector="Technology", country="CN")
E("ADANIENT.NS", "Adani Enterprises", "Adani", domain="adani.com", sector="Industrials", country="IN")
E("EQNR", "Equinor", "Equinor", domain="equinor.com", sector="Energy", country="NO")
E("GLNCY", "Glencore", "Glencore", domain="glencore.com", sector="Materials", country="CH")
E("LUNR", "Intuitive Machines", "Intuitive Machines", domain="intuitivemachines.com", sector="Industrials")
E("JOBY", "Joby Aviation", "Joby Aviation|Joby", domain="jobyaviation.com", sector="Industrials")
E("ACHR", "Archer Aviation", "Archer Aviation", domain="archer.com", sector="Industrials")
E("ZION", "Zions Bancorporation", "Zions", domain="zionsbancorporation.com", sector="Financials")
E("CMA", "Comerica", "Comerica", domain="comerica.com", sector="Financials")
E("FCNCA", "First Citizens BancShares", "First Citizens", domain="firstcitizens.com", sector="Financials")
E("BULL", "Webull", "Webull", domain="webull.com", sector="Financials")
E("GEMI", "Gemini Space Station", "Gemini exchange|Winklevoss Gemini|Gemini crypto", domain="gemini.com", sector="Financials")
E("FI", "Fiserv", "Fiserv|Clover POS", domain="fiserv.com", sector="Financials")
E("WU", "Western Union", "Western Union", domain="westernunion.com", sector="Financials")
E("SKX", "Skechers", "Skechers", domain="skechers.com", sector="Consumer Discretionary", delisted="2025-09-12")
E("LEVI", "Levi Strauss", "Levi Strauss|Levi's", domain="levistrauss.com", sector="Consumer Discretionary")
E("CBRL", "Cracker Barrel", "Cracker Barrel", domain="crackerbarrel.com", sector="Consumer Discretionary")
E("DIN", "Dine Brands", "Dine Brands|Applebee's|IHOP", domain="dinebrands.com", sector="Consumer Discretionary")
E("PZZA", "Papa John's", "Papa John's|Papa Johns", domain="papajohns.com", sector="Consumer Discretionary")
E("WING", "Wingstop", "Wingstop", domain="wingstop.com", sector="Consumer Discretionary")
E("TXRH", "Texas Roadhouse", "Texas Roadhouse", domain="texasroadhouse.com", sector="Consumer Discretionary")
E("EAT", "Brinker International", "Brinker|Chili's", domain="brinker.com", sector="Consumer Discretionary")
E("DEO", "Diageo", "Diageo", domain="diageo.com", sector="Consumer Staples", country="UK")
E("BF-B", "Brown-Forman", "Brown-Forman|Jack Daniel's", domain="brown-forman.com", sector="Consumer Staples", yf="BF-B")
E("LRLCY", "L'Oréal", "L'Oreal|L'Oréal", domain="loreal.com", sector="Consumer Staples", country="FR")
E("TKO", "TKO Group (WWE, UFC)", "TKO Group|WWE|UFC", domain="tkogrp.com", sector="Communication Services")
E("IHRT", "iHeartMedia", "iHeartMedia|iHeart", domain="iheartmedia.com", sector="Communication Services")
E("WMG", "Warner Music Group", "Warner Music", domain="wmg.com", sector="Communication Services")
E("RUM", "Rumble", "Rumble Inc|?Rumble", domain="rumble.com", sector="Communication Services")
E("DJT", "Trump Media & Technology", "Trump Media|Truth Social|DJT", domain="tmtgcorp.com", sector="Communication Services")
E("MOH", "Molina Healthcare", "Molina", domain="molinahealthcare.com", sector="Health Care")
E("THC", "Tenet Healthcare", "Tenet Healthcare", domain="tenethealth.com", sector="Health Care")
E("AZN", "AstraZeneca", "AstraZeneca|Astra Zeneca", domain="astrazeneca.com", sector="Health Care", country="UK")
E("GSK", "GSK", "GlaxoSmithKline|GSK", domain="gsk.com", sector="Health Care", country="UK")
E("SNY", "Sanofi", "Sanofi", domain="sanofi.com", sector="Health Care", country="FR")
E("RHHBY", "Roche", "Roche", domain="roche.com", sector="Health Care", country="CH")
E("BAYRY", "Bayer", "Bayer", domain="bayer.com", sector="Health Care", country="DE")
E("CAH", "Cardinal Health", "Cardinal Health", domain="cardinalhealth.com", sector="Health Care")
E("COR", "Cencora", "Cencora|AmerisourceBergen", domain="cencora.com", sector="Health Care")
E("LH", "Labcorp", "Labcorp|LabCorp", domain="labcorp.com", sector="Health Care")
E("DGX", "Quest Diagnostics", "Quest Diagnostics", domain="questdiagnostics.com", sector="Health Care")
E("EW", "Edwards Lifesciences", "Edwards Lifesciences", domain="edwards.com", sector="Health Care")
E("RMD", "ResMed", "ResMed|Resmed", domain="resmed.com", sector="Health Care")
E("HOUS", "Anywhere Real Estate", "Anywhere Real Estate|Realogy", domain="anywhere.re", sector="Real Estate")
E("EXPI", "eXp World Holdings", "eXp Realty|eXp World", domain="expworldholdings.com", sector="Real Estate")
E("PLD", "Prologis", "Prologis", domain="prologis.com", sector="Real Estate")
E("AMT", "American Tower", "American Tower", domain="americantower.com", sector="Real Estate")
E("SPG", "Simon Property Group", "Simon Property", domain="simon.com", sector="Real Estate")
E("O", "Realty Income", "Realty Income", domain="realtyincome.com", sector="Real Estate")
E("PSA", "Public Storage", "Public Storage", domain="publicstorage.com", sector="Real Estate")
E("EQIX", "Equinix", "Equinix", domain="equinix.com", sector="Real Estate")
E("DLR", "Digital Realty", "Digital Realty", domain="digitalrealty.com", sector="Real Estate")
E("TXT", "Textron", "Textron", domain="textron.com", sector="Industrials")
E("HII", "Huntington Ingalls", "Huntington Ingalls", domain="hii.com", sector="Industrials")
E("BAH", "Booz Allen Hamilton", "Booz Allen", domain="boozallen.com", sector="Industrials")
E("AXON", "Axon Enterprise", "Axon Enterprise|Axon", domain="axon.com", sector="Industrials")
E("SWK", "Stanley Black & Decker", "Stanley Black & Decker|Stanley Black and Decker", domain="stanleyblackanddecker.com", sector="Industrials")
E("WHR", "Whirlpool", "Whirlpool", domain="whirlpoolcorp.com", sector="Consumer Discretionary")
E("GNRC", "Generac", "Generac", domain="generac.com", sector="Industrials")
E("OTIS", "Otis Worldwide", "Otis Worldwide|Otis Elevator", domain="otis.com", sector="Industrials")
E("FAST", "Fastenal", "Fastenal", domain="fastenal.com", sector="Industrials")
E("GWW", "W.W. Grainger", "Grainger", domain="grainger.com", sector="Industrials")
E("EXC", "Exelon", "Exelon", domain="exeloncorp.com", sector="Utilities")
E("AEP", "American Electric Power", "American Electric Power", domain="aep.com", sector="Utilities")
E("EIX", "Edison International", "Edison International|Southern California Edison", domain="edison.com", sector="Utilities")
E("SRE", "Sempra", "Sempra", domain="sempra.com", sector="Utilities")
E("TLN", "Talen Energy", "Talen Energy|Talen", domain="talenenergy.com", sector="Utilities")
E("NRG", "NRG Energy", "NRG Energy|NRG", domain="nrg.com", sector="Utilities")
E("BE", "Bloom Energy", "Bloom Energy", domain="bloomenergy.com", sector="Industrials")
E("RIDE", "Lordstown Motors", "Lordstown", domain="lordstownmotors.com", sector="Consumer Discretionary", delisted="2023-06-27")
E("GOEV", "Canoo", "Canoo", domain="canoo.com", sector="Consumer Discretionary", delisted="2025-01-17")
E("PSNY", "Polestar", "Polestar", domain="polestar.com", sector="Consumer Discretionary", country="SE")
E("RGTI", "Rigetti Computing", "Rigetti", domain="rigetti.com", sector="Technology")
E("IONQ", "IonQ", "IonQ", domain="ionq.com", sector="Technology")
E("QBTS", "D-Wave Quantum", "D-Wave", domain="dwavequantum.com", sector="Technology")
E("ADI", "Analog Devices", "Analog Devices", domain="analog.com", sector="Technology")
E("NXPI", "NXP Semiconductors", "NXP", domain="nxp.com", sector="Technology", country="NL")
E("ON", "onsemi", "onsemi|ON Semiconductor", domain="onsemi.com", sector="Technology")
E("MCHP", "Microchip Technology", "Microchip Technology", domain="microchip.com", sector="Technology")
E("GFS", "GlobalFoundries", "GlobalFoundries|Global Foundries", domain="gf.com", sector="Technology")
E("WOLF", "Wolfspeed", "Wolfspeed", domain="wolfspeed.com", sector="Technology")
E("JNPR", "Juniper Networks", "Juniper Networks", domain="juniper.net", sector="Technology", delisted="2025-07-02")
E("ERIC", "Ericsson", "Ericsson", domain="ericsson.com", sector="Technology", country="SE")
E("GLW", "Corning", "Corning", domain="corning.com", sector="Technology")
E("SAP", "SAP", "SAP", domain="sap.com", sector="Technology", country="DE")
E("S", "SentinelOne", "SentinelOne|Sentinel One", domain="sentinelone.com", sector="Technology")
E("HUBS", "HubSpot", "HubSpot|Hubspot", domain="hubspot.com", sector="Technology")
E("GDDY", "GoDaddy", "GoDaddy|Go Daddy", domain="godaddy.com", sector="Technology")
E("SONO", "Sonos", "Sonos", domain="sonos.com", sector="Consumer Discretionary")
E("GPRO", "GoPro", "GoPro|Go Pro", domain="gopro.com", sector="Consumer Discretionary")
E("GRMN", "Garmin", "Garmin", domain="garmin.com", sector="Consumer Discretionary")
E("CCJ", "Cameco", "Cameco", domain="cameco.com", sector="Energy", country="CA")
E("KRKN", "Kraken (Payward)", "Kraken exchange|Kraken crypto", domain="kraken.com", sector="Financials")
E("CART.X", "placeholder", "", domain="")
ENTRIES = [e for e in ENTRIES if e[0] != "CART.X"]

# Drop the placeholder used to keep the international block tidy.
ENTRIES = [e for e in ENTRIES if e[0] != "ABNB.X" and e[2] != "" or e[3].get("etf")]
ENTRIES = [e for e in ENTRIES if e[0] != "ABNB.X"]

# Context patterns that should NOT count as a mention of the company.
EXCLUDE_PATTERNS = [
    r"Oracle of Omaha",
    # social-media plugs and platform references rather than the company
    r"\bon (Twitter|Instagram|Facebook|YouTube|LinkedIn|TikTok|Threads)\b",
    r"\b(Twitter|Instagram|Facebook|YouTube|LinkedIn) (handle|handles|page|pages|account|accounts|feed|channel|channels|followers|profile|video|videos|live|space|spaces|thread|threads|post|posts|comments?)\b",
    r"\b(follow|find|catch|join|see|watch|check out|hit|reach|DM|message) (us|me|him|her|them|Caleb|the show|the Express)\b[^.]{0,40}\b(Twitter|Instagram|Facebook|YouTube|LinkedIn|TikTok)\b",
    r"\b(Twitter|Instagram|YouTube|Facebook)[,/ ]+(and|or|&)? ?(Twitter|Instagram|YouTube|Facebook|TikTok|LinkedIn)\b",
    r"\btweet(s|ed|ing)?\b",
    r"Northwestern Kellogg|Kellogg School|Kellogg School of Management",
    r"Gap (EPS|earnings|accounting|basis|net|operating|measures?|numbers?|results?|profit|income|revenue)",
    r"non-?Gap\b",
    r"\b[A-Z][a-z]+ Block\b",
    r"Delta (variant|strain|wave|surge|cases|COVID|Covid|outbreak|fears|spread|infections|virus)",
    r"(COVID|Covid|coronavirus|virus|variant|vaccine|infection|pandemic|Omicron)[^.]{0,40}\bDelta\b",
    r"degrees? Celsius|Celsius (degrees?|warming)",
    r"Big Apple",
    r"Apple pie",
    r"Amazon (rain ?forest|river|basin)",
    r"Delta (variant|strain|wave)",
    r"Apollo (program|mission|\d+|astronaut)",
    r"Alphabet soup",
    r"Meta[- ]analysis",
    r"Shell (company|companies|game|shock)",
    r"Target(ed|ing|s)? (rate|range|price|the|a|an|for)",  # 'target rate' style phrasing
    r"Ford Foundation",
    r"Gerald Ford|Henry Ford|Harrison Ford|Tom Ford|Rob Ford|Christine Ford",
    r"Snap (back|election|judgment|decision|poll)",
    r"Block(ing|ed|s)? (trade|the|a|out)",
    r"Square (footage|feet|foot|one|off|Mile|Times)",
    r"Times Square",
    r"Zoom(ing|ed|s)? (in|out|call|calls|meeting|meetings|past|ahead|higher|lower)",
    r"Visa (application|requirements|program|holder|holders|waiver|policy|rules|restrictions)",
    r"H-?1B visa|student visa|work visa|travel visa|golden visa",
    r"Progressive (tax|taxes|taxation|policy|policies|left|Democrat|Democrats|wing|era)",
    r"Discover(ed|ing|s|y)?\b",
    r"Carnival (of|atmosphere|barker)",
    r"Gap (between|in|year|years|up|down|fill|is|of|to)",
    r"(wealth|income|wage|gender|pay|skills|output|funding|trade|budget|generation) gap",
    r"Southwest (border|region|desert|monsoon)",
    r"Lucid (dream|dreams|dreaming|moment|moments|explanation)",
    r"Snowflake (generation|effect)",
    r"Upstart (challenger|rival|rivals|company|companies|startup|startups)",
    r"Circle (back|of|the|around|K)",
    r"Arm(ed|s|ing)? (of|with|forces|race|sales|and|the|wrestling|twisting|chair)",
    r"Compass (point|rose|needle)",
    r"Toast(ed|ing)? (to|the|a|of)",
    r"Lemonade stand",
    r"Bullish (on|about|sentiment|signal|signals|case|call|calls|bets?|traders?|investors?|stance|outlook|momentum|run|trend|thesis|chart|charts|pattern|patterns|engulfing|reversal|flag|crossover|as|than|and|or|in|for|since|because|despite|until|when|while|again|enough)",
    r"Freedom (Caucus|of|to|from|Day|Convoy|Tower|fighters?)",
    r"Celsius (degrees?|scale|temperature)",
    r"Affirm(ed|ing|s|ative|ation)\b",
]

# Cue words: an ambiguous alias only counts if one of these appears nearby.
CUE_WORDS = [
    "stock", "stocks", "shares", "share price", "earnings", "quarter", "quarterly", "results",
    "report", "reports", "reported", "reporting", "ceo", "cfo", "founder", "ipo", "market cap",
    "valuation", "investors", "shareholders", "shareholder", "company", "companies", "retailer",
    "chipmaker", "automaker", "airline", "airlines", "bank", "lender", "insurer", "drugmaker",
    "rally", "rallied", "plunge", "plunged", "tumble", "tumbled", "surge", "surged", "soared",
    "slump", "slumped", "sell-off", "selloff", "buyback", "dividend", "revenue", "sales", "profit",
    "profits", "guidance", "ticker", "inc", "corp", "nasdaq", "nyse", "acquisition", "acquire",
    "acquired", "merger", "deal", "split", "wall street", "analyst", "analysts", "upgrade",
    "downgrade", "stores", "brand", "brands", "consumer", "customers", "outlook", "beat", "miss",
    "cut", "cuts", "layoffs", "trading", "traders", "options", "short", "squeeze", "meme", "listing",
]
